FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy requirements.txt
COPY ./requirements.txt /code/requirements.txt

# Install necessary dependencies for wkhtmltopdf
RUN apt-get update && apt-get install -y \
    wkhtmltopdf --fix-missing

# Install Python dependencies
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# Copy the rest of the application code
COPY ./backend/app /app

EXPOSE 8080
