FROM python:3.10-slim

# Install necessary dependencies for wkhtmltopdf
RUN apt-get update && \
    apt-get install -y --no-install-recommends wkhtmltopdf --fix-missing && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /backend

COPY ./backend .

WORKDIR /backend/app

# Install Python dependencies
RUN pip install --no-cache-dir --upgrade -r requirements.txt

EXPOSE 8080
