"""empty message

Revision ID: 1228477e0990
Revises: 4c48dda81447
Create Date: 2024-05-24 00:05:02.827745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1228477e0990'
down_revision: Union[str, None] = '4c48dda81447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printers', sa.Column('ip', sa.String(), nullable=True))
    op.add_column('printers', sa.Column('port', sa.Integer(), nullable=True))
    op.drop_index('ix_printers_address', table_name='printers')
    op.drop_index('ix_printers_city', table_name='printers')
    op.drop_index('ix_printers_state', table_name='printers')
    op.drop_index('ix_printers_zip_code', table_name='printers')
    op.drop_index('ix_printers_name', table_name='printers')
    op.create_index(op.f('ix_printers_name'), 'printers', ['name'], unique=False)
    op.create_index(op.f('ix_printers_ip'), 'printers', ['ip'], unique=False)
    op.create_index(op.f('ix_printers_port'), 'printers', ['port'], unique=False)
    op.drop_constraint('printers_restaurant_id_fkey', 'printers', type_='foreignkey')
    op.drop_column('printers', 'state')
    op.drop_column('printers', 'address')
    op.drop_column('printers', 'restaurant_id')
    op.drop_column('printers', 'city')
    op.drop_column('printers', 'zip_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printers', sa.Column('zip_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('printers', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('printers', sa.Column('restaurant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('printers', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('printers', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('printers_restaurant_id_fkey', 'printers', 'restaurants', ['restaurant_id'], ['id'])
    op.drop_index(op.f('ix_printers_port'), table_name='printers')
    op.drop_index(op.f('ix_printers_ip'), table_name='printers')
    op.drop_index(op.f('ix_printers_name'), table_name='printers')
    op.create_index('ix_printers_name', 'printers', ['name'], unique=True)
    op.create_index('ix_printers_zip_code', 'printers', ['zip_code'], unique=False)
    op.create_index('ix_printers_state', 'printers', ['state'], unique=False)
    op.create_index('ix_printers_city', 'printers', ['city'], unique=False)
    op.create_index('ix_printers_address', 'printers', ['address'], unique=False)
    op.drop_column('printers', 'port')
    op.drop_column('printers', 'ip')
    # ### end Alembic commands ###
