"""empty message

Revision ID: 203b9cd7e3f9
Revises: 06ac7c4db85e
Create Date: 2024-05-12 02:33:32.970376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '203b9cd7e3f9'
down_revision: Union[str, None] = '06ac7c4db85e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'price')
    # ### end Alembic commands ###
