"""empty message

Revision ID: 24e456ff5eb2
Revises: 58396468ce76
Create Date: 2024-05-28 12:05:09.285689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24e456ff5eb2'
down_revision: Union[str, None] = '58396468ce76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('cash_paid', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('card_paid', sa.Float(), nullable=True))
    op.drop_column('transactions', 'cash_given')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('cash_given', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'card_paid')
    op.drop_column('transactions', 'cash_paid')
    # ### end Alembic commands ###
