"""empty message

Revision ID: 46abee1cde5d
Revises: c66bf0c480d9
Create Date: 2024-05-23 17:08:19.212432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46abee1cde5d'
down_revision: Union[str, None] = 'c66bf0c480d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('tax', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('total_non_taxable', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('total_taxable', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('collected_tax', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'collected_tax')
    op.drop_column('orders', 'total_taxable')
    op.drop_column('orders', 'total_non_taxable')
    op.drop_column('orders', 'payment_method')
    op.drop_column('order_items', 'tax')
    # ### end Alembic commands ###
