"""empty message

Revision ID: 4c48dda81447
Revises: 46abee1cde5d
Create Date: 2024-05-23 23:31:30.999985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c48dda81447'
down_revision: Union[str, None] = '46abee1cde5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('city', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('state', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('zip_code', sa.String(), nullable=True))
    op.drop_index('ix_restaurants_email', table_name='restaurants')
    op.drop_index('ix_restaurants_phone_number', table_name='restaurants')
    op.create_index(op.f('ix_restaurants_city'), 'restaurants', ['city'], unique=False)
    op.create_index(op.f('ix_restaurants_state'), 'restaurants', ['state'], unique=False)
    op.create_index(op.f('ix_restaurants_zip_code'), 'restaurants', ['zip_code'], unique=False)
    op.drop_column('restaurants', 'tax_rate')
    op.drop_column('restaurants', 'phone_number')
    op.drop_column('restaurants', 'currency')
    op.drop_column('restaurants', 'email')
    op.drop_column('restaurants', 'timezone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('timezone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('tax_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_restaurants_zip_code'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_state'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_city'), table_name='restaurants')
    op.create_index('ix_restaurants_phone_number', 'restaurants', ['phone_number'], unique=False)
    op.create_index('ix_restaurants_email', 'restaurants', ['email'], unique=False)
    op.drop_column('restaurants', 'zip_code')
    op.drop_column('restaurants', 'state')
    op.drop_column('restaurants', 'city')
    # ### end Alembic commands ###
