"""empty message

Revision ID: 75e421fee8e9
Revises: 1228477e0990
Create Date: 2024-05-25 18:09:29.115016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75e421fee8e9'
down_revision: Union[str, None] = '1228477e0990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total_taxable')
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'collected_tax')
    op.drop_column('orders', 'total_non_taxable')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_non_taxable', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('collected_tax', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('total_taxable', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
