"""empty message

Revision ID: 895e223f803e
Revises: ce6fe4dfa94c
Create Date: 2024-08-20 19:32:02.238872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '895e223f803e'
down_revision: Union[str, None] = 'ce6fe4dfa94c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('last_interacted_at', sa.DateTime(), nullable=True))
    op.drop_column('orders', 'lastInteraction')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('lastInteraction', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'last_interacted_at')
    # ### end Alembic commands ###
