"""empty message

Revision ID: c66bf0c480d9
Revises: ce04536d6af9
Create Date: 2024-05-18 20:56:38.463973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c66bf0c480d9'
down_revision: Union[str, None] = 'ce04536d6af9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('tax_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'tax_rate')
    # ### end Alembic commands ###
