"""empty message

Revision ID: ce04536d6af9
Revises: 203b9cd7e3f9
Create Date: 2024-05-13 19:12:05.600887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce04536d6af9'
down_revision: Union[str, None] = '203b9cd7e3f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_name', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('customer_phone_number', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('complete_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_orders_customer_name'), 'orders', ['customer_name'], unique=False)
    op.create_index(op.f('ix_orders_customer_phone_number'), 'orders', ['customer_phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_customer_phone_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_name'), table_name='orders')
    op.drop_column('orders', 'complete_at')
    op.drop_column('orders', 'customer_phone_number')
    op.drop_column('orders', 'customer_name')
    # ### end Alembic commands ###
